import sys
import json
import os
import tempfile
import yt_dlp
import traceback

def parse_cookies(cookies_str):
    """
    Parses a cookie string (either JSON or Netscape format) and returns Netscape format content.
    """
    if not cookies_str:
        return None
        
    cookies_str_stripped = cookies_str.strip()
    if not cookies_str_stripped:
        return None
        
    # Check if it looks like JSON
    if cookies_str_stripped.startswith('[') and cookies_str_stripped.endswith(']'):
        try:
            cookies_data = json.loads(cookies_str_stripped)
            if isinstance(cookies_data, list):
                netscape_lines = ["# Netscape HTTP Cookie File\n# This file was generated by ClipVault\n"]
                for cookie in cookies_data:
                    domain = cookie.get("domain", "")
                    if not domain:
                        continue
                    # Format: domain \t flag \t path \t secure \t expiration \t name \t value
                    flag = "TRUE" if domain.startswith(".") else "FALSE"
                    path = cookie.get("path", "/")
                    secure = "TRUE" if cookie.get("secure", False) else "FALSE"
                    
                    # Expiration date: check various possible keys
                    expiration = 0
                    for key in ["expirationDate", "expiry", "expires", "expires_at"]:
                        if key in cookie and cookie[key] is not None:
                            try:
                                expiration = int(cookie[key])
                                break
                            except ValueError:
                                pass
                                
                    name = cookie.get("name", "")
                    value = cookie.get("value", "")
                    netscape_lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")
                
                return "".join(netscape_lines)
        except Exception:
            # Fallback if JSON parsing fails
            pass
            
    # Default to raw Netscape format
    # Ensure it starts with the header if it doesn't already
    if not cookies_str_stripped.startswith("# Netscape HTTP Cookie File"):
        return "# Netscape HTTP Cookie File\n" + cookies_str
        
    return cookies_str

def extract_metadata(url):
    ydl_opts = {
        'quiet': True,
        'no_warnings': True,
        'format': 'best',
        'skip_download': True,
    }

    # Add proxy support
    proxy_env = os.environ.get("INSTAGRAM_PROXY") or os.environ.get("PROXY_URL")
    if proxy_env:
        ydl_opts['proxy'] = proxy_env

    temp_cookie_file = None
    try:
        # 1. Check for cookie file configured via env variable (highest priority)
        cookies_env = os.environ.get("INSTAGRAM_COOKIES")
        if cookies_env:
            # Check if it's a file path
            if os.path.exists(cookies_env):
                ydl_opts['cookiefile'] = cookies_env
            else:
                # Assume it's a cookies string (Netscape or JSON format)
                # Write to a temporary file
                fd, temp_cookie_file = tempfile.mkstemp(suffix=".txt", prefix="cookies_")
                with os.fdopen(fd, 'w') as f:
                    parsed_cookies = parse_cookies(cookies_env)
                    f.write(parsed_cookies if parsed_cookies else cookies_env)
                ydl_opts['cookiefile'] = temp_cookie_file

        # 2. Otherwise check for local cookies.txt files in common locations
        else:
            possible_cookies = [
                'cookies.txt',
                'instagram-cookies.txt',
                os.path.join(os.path.dirname(__file__), 'cookies.txt'),
                os.path.join(os.path.dirname(__file__), 'instagram-cookies.txt'),
                os.path.join(os.getcwd(), 'cookies.txt'),
                os.path.join(os.getcwd(), 'instagram-cookies.txt'),
            ]
            for cp in possible_cookies:
                if os.path.exists(cp):
                    ydl_opts['cookiefile'] = cp
                    break

        # 3. Fallback: try to extract cookies from local browsers if running in development mode
        # and no cookiefile has been configured yet.
        if 'cookiefile' not in ydl_opts and os.environ.get("NODE_ENV") != "production":
            browsers = ['chrome', 'firefox', 'edge', 'brave', 'opera']
            for browser in browsers:
                try:
                    test_opts = dict(ydl_opts)
                    test_opts['cookiesfrombrowser'] = (browser,)
                    with yt_dlp.YoutubeDL(test_opts) as ydl:
                        pass
                    ydl_opts['cookiesfrombrowser'] = (browser,)
                    break
                except Exception:
                    pass

        try:
            import yt_dlp.version
            yt_dlp_version = yt_dlp.version.__version__
        except Exception:
            yt_dlp_version = "unknown"

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            
            metadata = {
                "success": True,
                "yt_dlp_version": yt_dlp_version,
                "data": {
                    "id": info.get("id"),
                    "title": info.get("title") or info.get("description", "")[:100],
                    "uploader": info.get("uploader"),
                    "thumbnail": info.get("thumbnail"),
                    "thumbnails": info.get("thumbnails"),
                    "duration": info.get("duration"),
                    "videoUrl": info.get("url"),
                    "formats": [{ "url": f.get("url"), "ext": f.get("ext"), "vcodec": f.get("vcodec") } for f in info.get("formats", [])]
                },
                "debug": info
            }
            return metadata
            
    except Exception as e:
        try:
            import yt_dlp.version
            yt_dlp_version = yt_dlp.version.__version__
        except Exception:
            yt_dlp_version = "unknown"
            
        error_msg = str(e)
        if any(keyword in error_msg.lower() for keyword in ["empty media response", "login required", "403", "sign in"]):
            error_msg += " (Tip: Hosted servers often need cookies or a residential proxy to download from Instagram. Please configure INSTAGRAM_COOKIES and/or INSTAGRAM_PROXY.)"

        return {
            "success": False,
            "yt_dlp_version": yt_dlp_version,
            "error": error_msg,
            "traceback": traceback.format_exc()
        }
    finally:
        if temp_cookie_file and os.path.exists(temp_cookie_file):
            try:
                os.remove(temp_cookie_file)
            except Exception:
                pass

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(json.dumps({"success": False, "error": "No URL provided"}))
        sys.exit(1)

    url = sys.argv[1]

    # Handle --version or -v
    if url == "--version" or url == "-v":
        try:
            import yt_dlp.version
            ver = yt_dlp.version.__version__
        except Exception:
            ver = "unknown"
        print(json.dumps({"success": True, "data": {"version": ver}}))
        sys.exit(0)

    # Handle --update
    if url == "--update":
        try:
            import subprocess
            # Run: pip install --upgrade yt-dlp
            res = subprocess.run(
                [sys.executable, "-m", "pip", "install", "--upgrade", "yt-dlp"],
                capture_output=True,
                text=True
            )
            if res.returncode == 0:
                import importlib
                import yt_dlp.version
                try:
                    importlib.reload(yt_dlp.version)
                except Exception:
                    pass
                new_ver = yt_dlp.version.__version__
                print(json.dumps({
                    "success": True,
                    "data": {
                        "message": f"yt-dlp updated successfully to version {new_ver}.",
                        "version": new_ver
                    }
                }))
                sys.exit(0)
            else:
                print(json.dumps({
                    "success": False,
                    "error": f"pip upgrade failed (code {res.returncode}): {res.stderr or res.stdout}"
                }))
                sys.exit(0)
        except Exception as e:
            print(json.dumps({
                "success": False,
                "error": f"Exception during upgrade: {str(e)}",
                "traceback": traceback.format_exc()
            }))
            sys.exit(0)

    result = extract_metadata(url)
    print(json.dumps(result))


